#!/bin/sh
#/etc/hotplug.d/button/01-radio-toggle
if [ "$BUTTON" = "BTN_2" ] && [ "$ACTION" = "pressed" ]; then 
	if [ -d /var/run/hostapd-phy0 -o -d /var/run/hostapd-phy1 ]; then 
		/sbin/wifi down; 
	else 
		/sbin/wifi up; 
	fi
fi